'use client';

import React, { useState, useEffect } from 'react';
import { FiCopy, FiCheck, FiSend, FiCode, FiShield, FiAlertTriangle, FiBookOpen, FiKey, FiSun, FiMoon } from 'react-icons/fi';
import { useTheme } from 'next-themes';
import Link from 'next/link';
import Image from 'next/image';

interface Endpoint {
  method: 'GET' | 'POST' | 'PUT';
  path: string;
  authType: 'Public' | 'Bearer pk_key' | 'Vendor JWT';
  description: string;
  bodyParams?: { name: string; type: string; required: boolean; description: string }[];
  queryParams?: { name: string; type: string; required: boolean; description: string }[];
  responseExample: any;
  requestExample?: any;
}

export default function DocsPage() {
  const [activeSection, setActiveSection] = useState('overview');
  const [copiedStates, setCopiedStates] = useState<{ [key: string]: boolean }>({});
  
  // Interactive console state
  const [consoleMethod, setConsoleMethod] = useState<'GET' | 'POST' | 'PUT'>('POST');
  const [consolePath, setConsolePath] = useState('/api/payments/check');
  const [consoleApiKey, setConsoleApiKey] = useState('');
  const [consoleBody, setConsoleBody] = useState('{\n  "utr": "652603702065"\n}');
  const [consoleResponse, setConsoleResponse] = useState<any>(null);
  const [consoleLoading, setConsoleLoading] = useState(false);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStates((prev) => ({ ...prev, [id]: true }));
    setTimeout(() => {
      setCopiedStates((prev) => ({ ...prev, [id]: false }));
    }, 2000);
  };

  const sections = [
    { id: 'overview', name: 'Overview' },
    { id: 'authentication', name: 'Authentication' },
    { id: 'payments', name: 'Payments API' },
    { id: 'orders', name: 'Orders API' },
    { id: 'payouts', name: 'Payouts API' },
    { id: 'zibot', name: 'ZiBot API' },
    { id: 'errors', name: 'Error Codes' }
  ];

  const payinEndpoints: Endpoint[] = [
    {
      method: 'POST',
      path: '/api/payments/update',
      authType: 'Bearer pk_key',
      description: 'Update/mark a payment as completed using the transaction UTR. Requires vendor secret key (pk_).',
      bodyParams: [
        { name: 'utr', type: 'string', required: true, description: '12-digit bank reference transaction ID (UTR)' },
        { name: 'amount', type: 'number', required: true, description: 'Transaction amount in INR' },
        { name: 'vendor_code', type: 'string', required: true, description: '6-character vendor code (e.g., AB1234)' }
      ],
      requestExample: {
        utr: '652603702065',
        amount: 500.00,
        vendor_code: 'ZV1001'
      },
      responseExample: {
        success: true,
        message: 'Payment verified and updated successfully',
        payment: {
          id: 104,
          utr: '652603702065',
          amount: 500.00,
          status: 'completed',
          payment_status: 'Succeeded'
        }
      }
    },
    {
      method: 'POST',
      path: '/api/payments/check',
      authType: 'Public',
      description: 'Verify payment completion status based on UTR. Publicly accessible endpoint.',
      bodyParams: [
        { name: 'utr', type: 'string', required: true, description: '12-digit transaction UTR to search' }
      ],
      requestExample: {
        utr: '652603702065'
      },
      responseExample: {
        success: true,
        status: 'Succeeded',
        amount: 500.00,
        checked_at: '2026-05-22T20:10:00Z'
      }
    },
    {
      method: 'GET',
      path: '/api/vendor/payment-info',
      authType: 'Vendor JWT',
      description: 'Get the registered payment profile details, active business UPI ID, and payment QR code dynamic components for the active vendor.',
      responseExample: {
        success: true,
        business_name: 'TechMart India',
        upi_id: 'techmart@ybl',
        vendor_code: 'ZV1001'
      }
    },
    {
      method: 'GET',
      path: '/api/vendor/payments',
      authType: 'Vendor JWT',
      description: 'List recent transactions with filtering and pagination parameters. Authenticated using JWT token.',
      queryParams: [
        { name: 'page', type: 'number', required: false, description: 'Page number for list (default: 1)' },
        { name: 'limit', type: 'number', required: false, description: 'Number of rows per page (default: 10)' }
      ],
      responseExample: {
        success: true,
        payments: [
          { id: 10, utr: '652603702065', amount: 500.00, status: 'completed', created_at: '2026-05-22T19:30:00Z' }
        ],
        pagination: { total: 1, page: 1, limit: 10 }
      }
    },
    {
      method: 'POST',
      path: '/api/v1/orders/:orderId/submit-utr',
      authType: 'Public',
      description: 'Submit payment proof (UTR reference) for a specific order generated by the system. Publicly accessible endpoint.',
      bodyParams: [
        { name: 'utr', type: 'string', required: true, description: '12-digit payment transaction UTR' }
      ],
      requestExample: {
        utr: '652603702065'
      },
      responseExample: {
        success: true,
        message: 'UTR submitted and pending confirmation',
        order: {
          id: 'ord_9182398129',
          amount: 500.00,
          status: 'Pending',
          utr: '652603702065'
        }
      }
    }
  ];

  const orderEndpoints: Endpoint[] = [
    {
      method: 'POST',
      path: '/api/v1/orders',
      authType: 'Bearer pk_key',
      description: 'Generate a new payment/checkout order for a customer. Returns a unique paymentUrl redirecting the user to the secure checkout page.',
      bodyParams: [
        { name: 'merchantOrderId', type: 'string', required: true, description: 'Unique tracking ID from your merchant app' },
        { name: 'amount', type: 'number', required: true, description: 'Order transaction amount in INR' },
        { name: 'currency', type: 'string', required: true, description: 'Standard ISO currency code (INR)' },
        { name: 'customerName', type: 'string', required: true, description: 'Name of the customer paying for the order' },
        { name: 'returnUrl', type: 'string', required: true, description: 'Redirect URL after payment verification' },
        { name: 'callbackUrl', type: 'string', required: true, description: 'Webhook destination URL to receive status notifications' },
        { name: 'vendorCode', type: 'string', required: true, description: 'Your 6-character vendor code (e.g. ZV1001)' }
      ],
      requestExample: {
        merchantOrderId: 'merchant_3289138',
        amount: 500.00,
        currency: 'INR',
        customerName: 'Aravind Kumar',
        returnUrl: 'https://myshop.com/payment-result',
        callbackUrl: 'https://api.myshop.com/webhooks/payments',
        vendorCode: 'ZV1001'
      },
      responseExample: {
        status: 'success',
        merchantOrderId: 'merchant_3289138',
        ztakeOrderId: 'ZTK9182398129',
        paymentUrl: 'https://pay.ztake.in/orders/ZTK9182398129',
        vendorCode: 'ZV1001',
        authMethod: 'api_key_vendor_code'
      }
    },
    {
      method: 'GET',
      path: '/api/v1/orders/:orderId',
      authType: 'Public',
      description: 'Fetch the real-time status of a checkout order generated by the system.',
      responseExample: {
        success: true,
        order: {
          order_id: 'ord_9182398129',
          merchant_order_id: 'merchant_3289138',
          amount: 500.00,
          currency: 'INR',
          status: 'Succeeded',
          customer_name: 'Aravind Kumar',
          payment_time: '2026-05-22T20:10:00Z'
        }
      }
    }
  ];

  const payoutEndpoints: Endpoint[] = [
    {
      method: 'GET',
      path: '/api/vendor/payouts',
      authType: 'Vendor JWT',
      description: 'Retrieve a list of processed payouts and current status for the active vendor. Authenticated using JWT token.',
      responseExample: {
        success: true,
        payouts: [
          {
            id: 42,
            amount: 15000.00,
            status: 'completed',
            beneficiary_name: 'Subash Chandra',
            reference_id: 'ref_238913981',
            utr: '652813098132',
            created_at: '2026-05-22T15:00:00Z'
          }
        ]
      }
    }
  ];

  const chatbotEndpoints: Endpoint[] = [
    {
      method: 'POST',
      path: '/api/v2/chat/message',
      authType: 'Bearer pk_key',
      description: 'Send a prompt or support question to your custom ZiBot instance. Integrates Claude API internally.',
      bodyParams: [
        { name: 'message', type: 'string', required: true, description: 'The text prompt to submit to ZiBot' },
        { name: 'session_id', type: 'string', required: false, description: 'Existing session ID to continue discussion thread context' }
      ],
      requestExample: {
        message: 'Where is my order status?',
        session_id: 'sess_1716382910_a2d8s9'
      },
      responseExample: {
        success: true,
        reply: 'I checked your details. The payment of Rs. 500 for order tech_3289138 has succeeded. Please reload your merchant portal.',
        session_id: 'sess_1716382910_a2d8s9',
        bot_name: 'ZiBot'
      }
    },
    {
      method: 'GET',
      path: '/api/v2/chat/history',
      authType: 'Bearer pk_key',
      description: 'Fetch chat log details for a session thread using its unique session ID.',
      queryParams: [
        { name: 'session_id', type: 'string', required: true, description: 'The session identifier to retrieve' }
      ],
      responseExample: {
        success: true,
        session_id: 'sess_1716382910_a2d8s9',
        messages: [
          { role: 'user', content: 'Where is my order status?' },
          { role: 'assistant', content: 'I checked your details. The payment of Rs. 500 for order tech_3289138 has succeeded.' }
        ],
        created_at: '2026-05-22T19:00:00Z',
        updated_at: '2026-05-22T19:02:00Z'
      }
    },
    {
      method: 'GET',
      path: '/api/v2/chat/config',
      authType: 'Bearer pk_key',
      description: 'Fetch the active support bot customizations for the vendor.',
      responseExample: {
        success: true,
        config: {
          system_prompt: 'You are a helpful payment support assistant. Answer questions about payment status.',
          bot_name: 'ZiBot',
          is_active: true
        }
      }
    },
    {
      method: 'PUT',
      path: '/api/v2/chat/config',
      authType: 'Bearer pk_key',
      description: 'Update support chatbot configurations like names and customized system prompts.',
      bodyParams: [
        { name: 'system_prompt', type: 'string', required: false, description: 'Base context directives for chatbot response styles' },
        { name: 'bot_name', type: 'string', required: false, description: 'Name of the support chatbot' },
        { name: 'is_active', type: 'boolean', required: false, description: 'Enable/disable chatbot instance' }
      ],
      requestExample: {
        system_prompt: 'You are custom support bot. Answer questions about UPI payments.',
        bot_name: 'PayHelp',
        is_active: true
      },
      responseExample: {
        success: true,
        message: 'ZiBot config updated'
      }
    }
  ];

  const handleTestConsole = async (e: React.FormEvent) => {
    e.preventDefault();
    setConsoleLoading(true);
    setConsoleResponse(null);
    try {
      const headers: any = {
        'Content-Type': 'application/json'
      };
      if (consoleApiKey) {
        headers['Authorization'] = `Bearer ${consoleApiKey}`;
      }

      const options: RequestInit = {
        method: consoleMethod,
        headers
      };

      if (consoleMethod !== 'GET' && consoleBody.trim()) {
        options.body = consoleBody;
      }

      const res = await fetch(`https://ztake.in${consolePath}`, options);
      const data = await res.json();
      setConsoleResponse({
        status: res.status,
        statusText: res.statusText,
        data
      });
    } catch (err: any) {
      setConsoleResponse({
        error: err.message || 'Network request failed'
      });
    } finally {
      setConsoleLoading(false);
    }
  };

  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className="flex min-h-screen text-[var(--layout-text-primary)]" style={{ background: 'var(--page-bg)' }}>
      {/* Sidebar - Theme responsive sidebar */}
      <aside className="w-64 border-r flex flex-col fixed h-screen overflow-y-auto"
        style={{
          background: 'var(--layout-sidebar-bg)',
          borderColor: 'var(--layout-sidebar-border)',
          color: 'var(--layout-text-secondary)',
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)'
        }}
      >
        <div className="p-6 border-b flex items-center justify-between" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
          <div className="flex items-center space-x-3">
            <Link href="/" className="flex items-center space-x-2.5 group">
              <Image src="/ztake-icon.png" alt="Ztake" width={26} height={26} className="rounded" />
              <span className="ztake-wordmark text-lg">ztake</span>
            </Link>
          </div>
          
          {/* Theme Toggle Button */}
          {mounted && (
            <button
              onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
              className="p-2 rounded-full hover:bg-[var(--layout-nav-hover-bg)] transition-colors text-[var(--layout-text-secondary)] hover:text-[var(--layout-text-primary)]"
              aria-label="Toggle theme"
            >
              {theme === 'dark' ? <FiSun className="w-4 h-4" /> : <FiMoon className="w-4 h-4" />}
            </button>
          )}
        </div>

        <nav className="flex-1 px-4 py-6 space-y-1.5">
          <div className="px-3 mb-2 text-[10px] font-bold tracking-wider uppercase opacity-60">
            API References
          </div>
          {sections.map((section) => (
            <button
              key={section.id}
              onClick={() => {
                setActiveSection(section.id);
                document.getElementById(section.id)?.scrollIntoView({ behavior: 'smooth' });
              }}
              className="w-full text-left px-3 py-2 rounded-lg text-sm font-medium transition-all duration-200"
              style={{
                background: activeSection === section.id ? 'var(--layout-nav-active-bg)' : 'transparent',
                color: activeSection === section.id ? 'var(--layout-text-active)' : 'var(--layout-text-secondary)',
                boxShadow: activeSection === section.id ? '0 2px 8px rgba(0,0,0,0.08)' : 'none'
              }}
              onMouseEnter={(e) => {
                if (activeSection !== section.id) {
                  e.currentTarget.style.background = 'var(--layout-nav-hover-bg)';
                  e.currentTarget.style.color = 'var(--layout-text-primary)';
                }
              }}
              onMouseLeave={(e) => {
                if (activeSection !== section.id) {
                  e.currentTarget.style.background = 'transparent';
                  e.currentTarget.style.color = 'var(--layout-text-secondary)';
                }
              }}
            >
              {section.name}
            </button>
          ))}
        </nav>
      </aside>

      {/* Main Content Area */}
      <main className="ml-64 flex-1 p-8 lg:p-12 max-w-5xl overflow-y-auto">
        {/* Header Banner */}
        <div className="mb-10 pb-6 border-b" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
          <div className="flex items-center space-x-2 font-semibold text-xs mb-2 text-zinc-550 dark:text-zinc-400">
            <span>DEVELOPER REFERENCE</span>
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight bg-gradient-to-r from-zinc-950 to-zinc-600 dark:from-white dark:to-zinc-400 bg-clip-text text-transparent">
            ZTake Payment Gateway API Docs
          </h1>
          <p className="mt-3 text-lg text-[var(--layout-text-secondary)]">
            Integrate UPI payment confirmation flows, track order statuses, manage payout distributions, and customize your site-support chatbot.
          </p>
          <div className="mt-4 flex items-center space-x-3 p-3 rounded-lg border w-fit" 
            style={{ 
              background: 'var(--glass-bg)', 
              borderColor: 'var(--layout-sidebar-border)',
              backdropFilter: 'blur(10px)',
              WebkitBackdropFilter: 'blur(10px)'
            }}
          >
            <span className="text-xs font-semibold text-[var(--layout-text-secondary)] uppercase">BASE URL:</span>
            <code className="text-sm font-mono text-[var(--layout-text-primary)]">https://ztake.in</code>
          </div>
        </div>

        {/* Section: Overview */}
        <section id="overview" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-4">Overview</h2>
          <div className="prose dark:prose-invert max-w-none text-[var(--layout-text-secondary)] space-y-4">
            <p>
              Welcome to the ZTake API portal. The endpoints described in this guide allow automated system interfaces to update records of bank transaction events, verify instant check-outs, process settlements, and control chatbot configurations.
            </p>
            <p>
              Our infrastructure is built for high speed and transaction stability, supporting instant merchant QR notifications, webhook status delivery, and AI chatbot modules.
            </p>
          </div>
        </section>

        {/* Section: Authentication */}
        <section id="authentication" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-4 flex items-center gap-2">
            <FiShield className="text-[var(--layout-text-primary)] opacity-80" /> Authentication
          </h2>
          <div className="space-y-4 text-[var(--layout-text-secondary)]">
            <p>
              The ZTake API verifies requests using Bearer tokens supplied in standard HTTP Authorization headers.
            </p>
            
            <div className="border rounded-xl p-6 space-y-4" 
              style={{ 
                background: 'var(--glass-bg)', 
                borderColor: 'var(--layout-sidebar-border)', 
                backdropFilter: 'blur(10px)',
                WebkitBackdropFilter: 'blur(10px)'
              }}
            >
              <div className="flex gap-4 items-start">
                <div className="mt-1 p-2 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-[var(--layout-text-primary)]">
                  <FiShield className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-[var(--layout-text-primary)]">Vendor JWT Token</h4>
                  <p className="text-sm mt-1 text-[var(--layout-text-secondary)]">
                    Obtained by calling `POST /api/auth/login`. This temporary token authenticates frontend vendor operations and dashboard lookups. It must be provided in the header as:
                  </p>
                  <pre className="mt-2 bg-black/40 border border-white/5 text-zinc-300 p-2.5 rounded-lg font-mono text-xs">Authorization: Bearer jwt_token_string</pre>
                </div>
              </div>

              <div className="flex gap-4 items-start border-t pt-4" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
                <div className="mt-1 p-2 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-[var(--layout-text-primary)]">
                  <FiKey className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-[var(--layout-text-primary)]">Secret API Key (Permanent)</h4>
                  <p className="text-sm mt-1 text-[var(--layout-text-secondary)]">
                    Found inside your dashboard Settings under the API Keys/Credential tab. Secret keys begin with the prefix `pk_`. Use this key for permanent backend services or server-to-server bot integrations.
                  </p>
                  <pre className="mt-2 bg-black/40 border border-white/5 text-zinc-300 p-2.5 rounded-lg font-mono text-xs">Authorization: Bearer pk_live_xxxxx</pre>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Section: Payments API */}
        <section id="payments" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-6">Payments API</h2>
          <div className="space-y-12">
            {payinEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: Orders API */}
        <section id="orders" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-6">Orders API</h2>
          <div className="space-y-12">
            {orderEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: Payouts API */}
        <section id="payouts" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-6">Payouts API</h2>
          <div className="space-y-12">
            {payoutEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: ZiBot API */}
        <section id="zibot" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-6">ZiBot Chatbot API</h2>
          <div className="space-y-12">
            {chatbotEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: Errors */}
        <section id="errors" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-[var(--layout-text-primary)] mb-4">Error Codes</h2>
          <p className="text-[var(--layout-text-secondary)] mb-6">
            Standard REST API HTTP response statuses returned on process outcomes:
          </p>
          <div className="overflow-x-auto border rounded-xl" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
            <table className="w-full text-left border-collapse text-sm">
              <thead>
                <tr className="bg-zinc-50/20 dark:bg-zinc-900/20 text-[var(--layout-text-secondary)] text-xs font-semibold uppercase border-b"
                  style={{ borderColor: 'var(--layout-sidebar-border)' }}
                >
                  <th className="px-6 py-4">Status Code</th>
                  <th className="px-6 py-4">Error Name</th>
                  <th className="px-6 py-4">Typical Reason</th>
                </tr>
              </thead>
              <tbody className="divide-y text-[var(--layout-text-primary)]" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
                <tr className="hover:bg-zinc-500/5 transition">
                  <td className="px-6 py-4 font-mono font-bold text-red-500 dark:text-red-400">400</td>
                  <td className="px-6 py-4 font-semibold">Bad Request</td>
                  <td className="px-6 py-4 text-[var(--layout-text-secondary)]">Missing parameters, invalid types, or request content limit errors.</td>
                </tr>
                <tr className="hover:bg-zinc-500/5 transition">
                  <td className="px-6 py-4 font-mono font-bold text-red-500 dark:text-red-400">401</td>
                  <td className="px-6 py-4 font-semibold">Unauthorized</td>
                  <td className="px-6 py-4 text-[var(--layout-text-secondary)]">Bearer token is missing, invalid, or belongs to a disabled account.</td>
                </tr>
                <tr className="hover:bg-zinc-500/5 transition">
                  <td className="px-6 py-4 font-mono font-bold text-red-500 dark:text-red-400">403</td>
                  <td className="px-6 py-4 font-semibold">Forbidden</td>
                  <td className="px-6 py-4 text-[var(--layout-text-secondary)]">Resource permissions prevent active user context from accessing.</td>
                </tr>
                <tr className="hover:bg-zinc-500/5 transition">
                  <td className="px-6 py-4 font-mono font-bold text-red-500 dark:text-red-400">404</td>
                  <td className="px-6 py-4 font-semibold">Not Found</td>
                  <td className="px-6 py-4 text-[var(--layout-text-secondary)]">Requested resource, payment UTR, or session context key does not exist.</td>
                </tr>
                <tr className="hover:bg-zinc-500/5 transition">
                  <td className="px-6 py-4 font-mono font-bold text-red-500 dark:text-red-400">429</td>
                  <td className="px-6 py-4 font-semibold">Too Many Requests</td>
                  <td className="px-6 py-4 text-[var(--layout-text-secondary)]">Rate limits exceeded. Reduce invocation frequencies.</td>
                </tr>
                <tr className="hover:bg-zinc-500/5 transition">
                  <td className="px-6 py-4 font-mono font-bold text-red-500 dark:text-red-400">500</td>
                  <td className="px-6 py-4 font-semibold">Internal Server Error</td>
                  <td className="px-6 py-4 text-[var(--layout-text-secondary)]">An unexpected malfunction occurred within payment platform routines.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* Section: Try It Console */}
        <section id="try-it" className="scroll-mt-6 border-t pt-12" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
          <div className="border rounded-2xl shadow-xl overflow-hidden"
            style={{ 
              background: 'var(--glass-bg)', 
              borderColor: 'var(--layout-sidebar-border)',
              backdropFilter: 'blur(20px)',
              WebkitBackdropFilter: 'blur(20px)'
            }}
          >
            <div className="p-6 border-b flex items-center justify-between bg-zinc-50/20 dark:bg-zinc-900/20"
              style={{ borderColor: 'var(--layout-sidebar-border)' }}
            >
              <div className="flex items-center space-x-3">
                <div className="p-2 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-[var(--layout-text-primary)]">
                  <FiCode className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-[var(--layout-text-primary)] text-lg">Interactive API Playground</h3>
                  <p className="text-xs text-[var(--layout-text-secondary)]">Test gateway requests live inside your browser</p>
                </div>
              </div>
            </div>

            <form onSubmit={handleTestConsole} className="p-6 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-xs font-semibold uppercase text-[var(--layout-text-secondary)] mb-2">HTTP Method &amp; Path</label>
                  <div className="flex space-x-2">
                    <select
                      value={consoleMethod}
                      onChange={(e) => setConsoleMethod(e.target.value as any)}
                      className="input-field font-bold cursor-pointer"
                    >
                      <option value="GET">GET</option>
                      <option value="POST">POST</option>
                      <option value="PUT">PUT</option>
                    </select>
                    <input
                      type="text"
                      value={consolePath}
                      onChange={(e) => setConsolePath(e.target.value)}
                      placeholder="/api/payments/check"
                      className="flex-1 input-field font-mono"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold uppercase text-[var(--layout-text-secondary)] mb-2">Bearer Token (Authorization)</label>
                  <input
                    type="password"
                    value={consoleApiKey}
                    onChange={(e) => setConsoleApiKey(e.target.value)}
                    placeholder="pk_live_..."
                    className="w-full input-field font-mono"
                  />
                </div>
              </div>

              {consoleMethod !== 'GET' && (
                <div>
                  <label className="block text-xs font-semibold uppercase text-[var(--layout-text-secondary)] mb-2">JSON Request Body</label>
                  <textarea
                    value={consoleBody}
                    onChange={(e) => setConsoleBody(e.target.value)}
                    rows={4}
                    className="w-full input-field font-mono text-sm"
                  />
                </div>
              )}

              <button
                type="submit"
                disabled={consoleLoading}
                className="w-full glass-button-primary py-3 px-4 transition duration-150 flex items-center justify-center space-x-2 shadow-lg"
              >
                {consoleLoading ? (
                  <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                ) : (
                  <>
                    <FiSend />
                    <span>Send Request to Live Endpoint</span>
                  </>
                )}
              </button>
            </form>

            {consoleResponse && (
              <div className="p-6 border-t space-y-3 bg-zinc-50/10 dark:bg-zinc-900/10" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold uppercase text-[var(--layout-text-secondary)]">Server Response</span>
                  {consoleResponse.status && (
                    <span
                      className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                        consoleResponse.status < 300
                          ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400'
                          : 'bg-red-500/20 text-red-600 dark:text-red-400'
                      }`}
                    >
                      HTTP {consoleResponse.status} {consoleResponse.statusText}
                    </span>
                  )}
                </div>
                <pre className="bg-black/40 border border-white/5 p-4 rounded-xl font-mono text-xs overflow-x-auto text-zinc-300">
                  {JSON.stringify(consoleResponse.data || consoleResponse, null, 2)}
                </pre>
              </div>
            )}
          </div>
        </section>
      </main>
    </div>
  );
}
function EndpointCard({
  endpoint,
  copiedStates,
  copyToClipboard
}: {
  endpoint: Endpoint;
  copiedStates: { [key: string]: boolean };
  copyToClipboard: (text: string, id: string) => void;
}) {
  const methodColors = {
    GET: 'bg-zinc-100 dark:bg-zinc-800/60 text-zinc-900 dark:text-zinc-105 border-zinc-200 dark:border-zinc-700/60',
    POST: 'bg-zinc-100 dark:bg-zinc-800/60 text-zinc-900 dark:text-zinc-105 border-zinc-200 dark:border-zinc-700/60',
    PUT: 'bg-zinc-100 dark:bg-zinc-800/60 text-zinc-900 dark:text-zinc-105 border-zinc-200 dark:border-zinc-700/60'
  };

  const id = `${endpoint.method}-${endpoint.path}`;

  return (
    <div className="border rounded-2xl shadow-[0_4px_24px_rgba(0,0,0,0.02)] transition overflow-hidden"
      style={{ 
        background: 'var(--glass-bg)', 
        borderColor: 'var(--layout-sidebar-border)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)'
      }}
    >
      {/* Top Banner */}
      <div className="p-6 border-b flex flex-wrap gap-4 items-center justify-between bg-zinc-50/20 dark:bg-zinc-900/20"
        style={{ borderColor: 'var(--layout-sidebar-border)' }}
      >
        <div className="flex items-center space-x-3 flex-1 min-w-0">
          <span className={`text-xs font-bold px-3 py-1.5 rounded-lg border ${methodColors[endpoint.method]}`}>
            {endpoint.method}
          </span>
          <code className="text-sm font-mono font-semibold text-[var(--layout-text-primary)] truncate">
            {endpoint.path}
          </code>
        </div>
        <div className="flex items-center space-x-2">
          <span className="text-xs bg-zinc-100 dark:bg-zinc-800 text-[var(--layout-text-secondary)] px-2.5 py-1 rounded-full font-medium border border-zinc-250/20 dark:border-zinc-700/20">
            Auth: {endpoint.authType}
          </span>
        </div>
      </div>

      <div className="p-6 space-y-6">
        <div>
          <p className="text-sm text-[var(--layout-text-secondary)] leading-relaxed">{endpoint.description}</p>
        </div>

        {/* Request Query/Body Params */}
        {endpoint.bodyParams && endpoint.bodyParams.length > 0 && (
          <div>
            <h4 className="text-xs font-bold uppercase text-[var(--layout-text-secondary)] tracking-wider mb-3">Request Body Properties</h4>
            <div className="overflow-x-auto border rounded-xl" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="text-[var(--layout-text-secondary)] uppercase font-semibold border-b bg-zinc-50/20 dark:bg-zinc-900/20"
                    style={{ borderColor: 'var(--layout-sidebar-border)' }}
                  >
                    <th className="px-4 py-3">Property</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Requirement</th>
                    <th className="px-4 py-3">Description</th>
                  </tr>
                </thead>
                <tbody className="divide-y text-[var(--layout-text-primary)]" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
                  {endpoint.bodyParams.map((param, index) => (
                    <tr key={index} className="hover:bg-zinc-500/5 transition">
                      <td className="px-4 py-3 font-mono font-bold">{param.name}</td>
                      <td className="px-4 py-3 text-[var(--layout-text-secondary)] font-mono">{param.type}</td>
                      <td className="px-4 py-3">
                        {param.required ? (
                          <span className="text-red-500 font-semibold bg-red-500/10 px-2 py-0.5 rounded">required</span>
                        ) : (
                          <span className="text-zinc-400 bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 rounded">optional</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-[var(--layout-text-secondary)]">{param.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Query Params */}
        {endpoint.queryParams && endpoint.queryParams.length > 0 && (
          <div>
            <h4 className="text-xs font-bold uppercase text-[var(--layout-text-secondary)] tracking-wider mb-3">Query Parameters</h4>
            <div className="overflow-x-auto border rounded-xl" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="text-[var(--layout-text-secondary)] uppercase font-semibold border-b bg-zinc-50/20 dark:bg-zinc-900/20"
                    style={{ borderColor: 'var(--layout-sidebar-border)' }}
                  >
                    <th className="px-4 py-3">Param</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Requirement</th>
                    <th className="px-4 py-3">Description</th>
                  </tr>
                </thead>
                <tbody className="divide-y text-[var(--layout-text-primary)]" style={{ borderColor: 'var(--layout-sidebar-border)' }}>
                  {endpoint.queryParams.map((param, index) => (
                    <tr key={index} className="hover:bg-zinc-500/5 transition">
                      <td className="px-4 py-3 font-mono font-bold">{param.name}</td>
                      <td className="px-4 py-3 text-[var(--layout-text-secondary)] font-mono">{param.type}</td>
                      <td className="px-4 py-3">
                        {param.required ? (
                          <span className="text-red-500 font-semibold bg-red-500/10 px-2 py-0.5 rounded">required</span>
                        ) : (
                          <span className="text-zinc-400 bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 rounded">optional</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-[var(--layout-text-secondary)]">{param.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Request / Response Tab Code Blocks */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
          {endpoint.requestExample && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs font-semibold text-[var(--layout-text-secondary)] uppercase">
                <span>Example Payload</span>
                <button
                  onClick={() => copyToClipboard(JSON.stringify(endpoint.requestExample, null, 2), `${id}-req`)}
                  className="flex items-center space-x-1 hover:text-[var(--layout-text-primary)] transition"
                >
                  {copiedStates[`${id}-req`] ? <FiCheck className="text-emerald-500" /> : <FiCopy />}
                  <span>{copiedStates[`${id}-req`] ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
              <pre className="bg-black/40 border border-white/5 p-4 rounded-xl font-mono text-xs overflow-x-auto text-zinc-300 max-h-60">
                {JSON.stringify(endpoint.requestExample, null, 2)}
              </pre>
            </div>
          )}
          
          <div className={endpoint.requestExample ? 'space-y-2' : 'col-span-2 space-y-2'}>
            <div className="flex items-center justify-between text-xs font-semibold text-[var(--layout-text-secondary)] uppercase">
              <span>Example Response</span>
              <button
                onClick={() => copyToClipboard(JSON.stringify(endpoint.responseExample, null, 2), `${id}-resp`)}
                className="flex items-center space-x-1 hover:text-[var(--layout-text-primary)] transition"
              >
                {copiedStates[`${id}-resp`] ? <FiCheck className="text-emerald-500" /> : <FiCopy />}
                <span>{copiedStates[`${id}-resp`] ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
            <pre className="bg-black/40 border border-white/5 p-4 rounded-xl font-mono text-xs overflow-x-auto text-zinc-300 max-h-60">
              {JSON.stringify(endpoint.responseExample, null, 2)}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
