'use client';

import React, { useState } from 'react';
import { FiCopy, FiCheck, FiSend, FiCode, FiShield, FiAlertTriangle, FiBookOpen, FiKey } from 'react-icons/fi';

interface Endpoint {
  method: 'GET' | 'POST' | 'PUT';
  path: string;
  authType: 'Public' | 'Bearer pk_key' | 'Vendor JWT';
  description: string;
  bodyParams?: { name: string; type: string; required: boolean; description: string }[];
  queryParams?: { name: string; type: string; required: boolean; description: string }[];
  responseExample: any;
  requestExample?: any;
}

export default function DocsPage() {
  const [activeSection, setActiveSection] = useState('overview');
  const [copiedStates, setCopiedStates] = useState<{ [key: string]: boolean }>({});
  
  // Interactive console state
  const [consoleMethod, setConsoleMethod] = useState<'GET' | 'POST' | 'PUT'>('POST');
  const [consolePath, setConsolePath] = useState('/api/payments/check');
  const [consoleApiKey, setConsoleApiKey] = useState('');
  const [consoleBody, setConsoleBody] = useState('{\n  "utr": "652603702065"\n}');
  const [consoleResponse, setConsoleResponse] = useState<any>(null);
  const [consoleLoading, setConsoleLoading] = useState(false);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStates((prev) => ({ ...prev, [id]: true }));
    setTimeout(() => {
      setCopiedStates((prev) => ({ ...prev, [id]: false }));
    }, 2000);
  };

  const sections = [
    { id: 'overview', name: 'Overview' },
    { id: 'authentication', name: 'Authentication' },
    { id: 'payments', name: 'Payments API' },
    { id: 'orders', name: 'Orders API' },
    { id: 'payouts', name: 'Payouts API' },
    { id: 'zibot', name: 'ZiBot API' },
    { id: 'errors', name: 'Error Codes' }
  ];

  const payinEndpoints: Endpoint[] = [
    {
      method: 'POST',
      path: '/api/payments/update',
      authType: 'Bearer pk_key',
      description: 'Update/mark a payment as completed using the transaction UTR. Requires vendor secret key (pk_).',
      bodyParams: [
        { name: 'utr', type: 'string', required: true, description: '12-digit bank reference transaction ID (UTR)' },
        { name: 'amount', type: 'number', required: true, description: 'Transaction amount in INR' },
        { name: 'vendor_code', type: 'string', required: true, description: '6-character vendor code (e.g., AB1234)' }
      ],
      requestExample: {
        utr: '652603702065',
        amount: 500.00,
        vendor_code: 'ZV1001'
      },
      responseExample: {
        success: true,
        message: 'Payment verified and updated successfully',
        payment: {
          id: 104,
          utr: '652603702065',
          amount: 500.00,
          status: 'completed',
          payment_status: 'Succeeded'
        }
      }
    },
    {
      method: 'POST',
      path: '/api/payments/check',
      authType: 'Public',
      description: 'Verify payment completion status based on UTR. Publicly accessible endpoint.',
      bodyParams: [
        { name: 'utr', type: 'string', required: true, description: '12-digit transaction UTR to search' }
      ],
      requestExample: {
        utr: '652603702065'
      },
      responseExample: {
        success: true,
        status: 'Succeeded',
        amount: 500.00,
        checked_at: '2026-05-22T20:10:00Z'
      }
    },
    {
      method: 'GET',
      path: '/api/vendor/payment-info',
      authType: 'Vendor JWT',
      description: 'Get the registered payment profile details, active business UPI ID, and payment QR code dynamic components for the active vendor.',
      responseExample: {
        success: true,
        business_name: 'TechMart India',
        upi_id: 'techmart@ybl',
        vendor_code: 'ZV1001'
      }
    },
    {
      method: 'GET',
      path: '/api/vendor/payments',
      authType: 'Vendor JWT',
      description: 'List recent transactions with filtering and pagination parameters. Authenticated using JWT token.',
      queryParams: [
        { name: 'page', type: 'number', required: false, description: 'Page number for list (default: 1)' },
        { name: 'limit', type: 'number', required: false, description: 'Number of rows per page (default: 10)' }
      ],
      responseExample: {
        success: true,
        payments: [
          { id: 10, utr: '652603702065', amount: 500.00, status: 'completed', created_at: '2026-05-22T19:30:00Z' }
        ],
        pagination: { total: 1, page: 1, limit: 10 }
      }
    },
    {
      method: 'POST',
      path: '/api/v1/orders/:orderId/submit-utr',
      authType: 'Public',
      description: 'Submit payment proof (UTR reference) for a specific order generated by the system. Publicly accessible endpoint.',
      bodyParams: [
        { name: 'utr', type: 'string', required: true, description: '12-digit payment transaction UTR' }
      ],
      requestExample: {
        utr: '652603702065'
      },
      responseExample: {
        success: true,
        message: 'UTR submitted and pending confirmation',
        order: {
          id: 'ord_9182398129',
          amount: 500.00,
          status: 'Pending',
          utr: '652603702065'
        }
      }
    }
  ];

  const orderEndpoints: Endpoint[] = [
    {
      method: 'GET',
      path: '/api/v1/orders/:orderId',
      authType: 'Public',
      description: 'Fetch the real-time status of a checkout order generated by the system.',
      responseExample: {
        success: true,
        order: {
          order_id: 'ord_9182398129',
          merchant_order_id: 'merchant_3289138',
          amount: 500.00,
          currency: 'INR',
          status: 'Succeeded',
          customer_name: 'Aravind Kumar',
          payment_time: '2026-05-22T20:10:00Z'
        }
      }
    }
  ];

  const payoutEndpoints: Endpoint[] = [
    {
      method: 'GET',
      path: '/api/vendor/payouts',
      authType: 'Vendor JWT',
      description: 'Retrieve a list of processed payouts and current status for the active vendor. Authenticated using JWT token.',
      responseExample: {
        success: true,
        payouts: [
          {
            id: 42,
            amount: 15000.00,
            status: 'completed',
            beneficiary_name: 'Subash Chandra',
            reference_id: 'ref_238913981',
            utr: '652813098132',
            created_at: '2026-05-22T15:00:00Z'
          }
        ]
      }
    }
  ];

  const chatbotEndpoints: Endpoint[] = [
    {
      method: 'POST',
      path: '/api/v2/chat/message',
      authType: 'Bearer pk_key',
      description: 'Send a prompt or support question to your custom ZiBot instance. Integrates Claude API internally.',
      bodyParams: [
        { name: 'message', type: 'string', required: true, description: 'The text prompt to submit to ZiBot' },
        { name: 'session_id', type: 'string', required: false, description: 'Existing session ID to continue discussion thread context' }
      ],
      requestExample: {
        message: 'Where is my order status?',
        session_id: 'sess_1716382910_a2d8s9'
      },
      responseExample: {
        success: true,
        reply: 'I checked your details. The payment of Rs. 500 for order tech_3289138 has succeeded. Please reload your merchant portal.',
        session_id: 'sess_1716382910_a2d8s9',
        bot_name: 'ZiBot'
      }
    },
    {
      method: 'GET',
      path: '/api/v2/chat/history',
      authType: 'Bearer pk_key',
      description: 'Fetch chat log details for a session thread using its unique session ID.',
      queryParams: [
        { name: 'session_id', type: 'string', required: true, description: 'The session identifier to retrieve' }
      ],
      responseExample: {
        success: true,
        session_id: 'sess_1716382910_a2d8s9',
        messages: [
          { role: 'user', content: 'Where is my order status?' },
          { role: 'assistant', content: 'I checked your details. The payment of Rs. 500 for order tech_3289138 has succeeded.' }
        ],
        created_at: '2026-05-22T19:00:00Z',
        updated_at: '2026-05-22T19:02:00Z'
      }
    },
    {
      method: 'GET',
      path: '/api/v2/chat/config',
      authType: 'Bearer pk_key',
      description: 'Fetch the active support bot customizations for the vendor.',
      responseExample: {
        success: true,
        config: {
          system_prompt: 'You are a helpful payment support assistant. Answer questions about payment status.',
          bot_name: 'ZiBot',
          is_active: true
        }
      }
    },
    {
      method: 'PUT',
      path: '/api/v2/chat/config',
      authType: 'Bearer pk_key',
      description: 'Update support chatbot configurations like names and customized system prompts.',
      bodyParams: [
        { name: 'system_prompt', type: 'string', required: false, description: 'Base context directives for chatbot response styles' },
        { name: 'bot_name', type: 'string', required: false, description: 'Name of the support chatbot' },
        { name: 'is_active', type: 'boolean', required: false, description: 'Enable/disable chatbot instance' }
      ],
      requestExample: {
        system_prompt: 'You are custom support bot. Answer questions about UPI payments.',
        bot_name: 'PayHelp',
        is_active: true
      },
      responseExample: {
        success: true,
        message: 'ZiBot config updated'
      }
    }
  ];

  const handleTestConsole = async (e: React.FormEvent) => {
    e.preventDefault();
    setConsoleLoading(true);
    setConsoleResponse(null);
    try {
      const headers: any = {
        'Content-Type': 'application/json'
      };
      if (consoleApiKey) {
        headers['Authorization'] = `Bearer ${consoleApiKey}`;
      }

      const options: RequestInit = {
        method: consoleMethod,
        headers
      };

      if (consoleMethod !== 'GET' && consoleBody.trim()) {
        options.body = consoleBody;
      }

      const res = await fetch(`https://ztake.in${consolePath}`, options);
      const data = await res.json();
      setConsoleResponse({
        status: res.status,
        statusText: res.statusText,
        data
      });
    } catch (err: any) {
      setConsoleResponse({
        error: err.message || 'Network request failed'
      });
    } finally {
      setConsoleLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-200">
      {/* Sidebar - Dark theme sidebar */}
      <aside className="w-64 bg-slate-900 text-slate-300 border-r border-slate-800 flex flex-col fixed h-screen overflow-y-auto">
        <div className="p-6 border-b border-slate-800 flex items-center space-x-3">
          <div className="bg-primary-600 p-2 rounded-lg text-white">
            <FiBookOpen className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white tracking-wide">ZTake Docs</h1>
            <p className="text-xs text-slate-500">v2.0.0 API Specification</p>
          </div>
        </div>

        <nav className="flex-1 px-4 py-6 space-y-2">
          {sections.map((section) => (
            <button
              key={section.id}
              onClick={() => {
                setActiveSection(section.id);
                document.getElementById(section.id)?.scrollIntoView({ behavior: 'smooth' });
              }}
              className={`w-full text-left px-3 py-2 rounded-lg text-sm font-medium transition-all ${
                activeSection === section.id
                  ? 'bg-primary-600 text-white shadow-md'
                  : 'hover:bg-slate-800 hover:text-slate-100'
              }`}
            >
              {section.name}
            </button>
          ))}
        </nav>
      </aside>

      {/* Main Content Area */}
      <main className="ml-64 flex-1 p-8 lg:p-12 max-w-5xl overflow-y-auto">
        {/* Header Banner */}
        <div className="mb-10 pb-6 border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center space-x-2 text-primary-600 dark:text-primary-400 font-semibold text-sm mb-2">
            <span>DEVELOPER REFERENCE</span>
          </div>
          <h1 className="text-4xl font-extrabold text-slate-950 dark:text-white tracking-tight">
            ZTake Payment Gateway API Docs
          </h1>
          <p className="mt-3 text-lg text-slate-600 dark:text-slate-400">
            Integrate UPI payment confirmation flows, track order statuses, manage payout distributions, and customize your site-support chatbot.
          </p>
          <div className="mt-4 flex items-center space-x-3 bg-white dark:bg-slate-850 p-3 rounded-lg border border-slate-250 dark:border-slate-800 w-fit">
            <span className="text-xs font-semibold text-slate-400 uppercase">BASE URL:</span>
            <code className="text-sm font-mono text-primary-600 dark:text-primary-400">https://ztake.in</code>
          </div>
        </div>

        {/* Section: Overview */}
        <section id="overview" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Overview</h2>
          <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-450 space-y-4">
            <p>
              Welcome to the ZTake API portal. The endpoints described in this guide allow automated system interfaces to update records of bank transaction events, verify instant check-outs, process settlements, and control chatbot configurations.
            </p>
            <p>
              Our infrastructure is built for high speed and transaction stability, supporting instant merchant QR notifications, webhook status delivery, and AI chatbot modules.
            </p>
          </div>
        </section>

        {/* Section: Authentication */}
        <section id="authentication" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
            <FiShield className="text-primary-500" /> Authentication
          </h2>
          <div className="space-y-4 text-slate-600 dark:text-slate-455">
            <p>
              The ZTake API verifies requests using Bearer tokens supplied in standard HTTP Authorization headers.
            </p>
            
            <div className="bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-800 rounded-xl p-6 space-y-4">
              <div className="flex gap-4 items-start">
                <div className="mt-1 bg-amber-50 dark:bg-amber-950 p-2 rounded-lg text-amber-600">
                  <FiShield className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-slate-900 dark:text-white">Vendor JWT Token</h4>
                  <p className="text-sm mt-1 text-slate-500">
                    Obtained by calling `POST /api/auth/login`. This temporary token authenticates frontend vendor operations and dashboard lookups. It must be provided in the header as:
                  </p>
                  <pre className="mt-2 bg-slate-900 text-slate-200 p-2 rounded font-mono text-xs">Authorization: Bearer jwt_token_string</pre>
                </div>
              </div>

              <div className="flex gap-4 items-start border-t border-slate-100 dark:border-slate-800 pt-4">
                <div className="mt-1 bg-blue-50 dark:bg-blue-950 p-2 rounded-lg text-blue-600">
                  <FiKey className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-slate-900 dark:text-white">Secret API Key (Permanent)</h4>
                  <p className="text-sm mt-1 text-slate-500">
                    Found inside your dashboard Settings under the API Keys/Credential tab. Secret keys begin with the prefix `pk_`. Use this key for permanent backend services or server-to-server bot integrations.
                  </p>
                  <pre className="mt-2 bg-slate-900 text-slate-200 p-2 rounded font-mono text-xs">Authorization: Bearer pk_live_xxxxx</pre>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Section: Payments API */}
        <section id="payments" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Payments API</h2>
          <div className="space-y-12">
            {payinEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: Orders API */}
        <section id="orders" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Orders API</h2>
          <div className="space-y-12">
            {orderEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: Payouts API */}
        <section id="payouts" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Payouts API</h2>
          <div className="space-y-12">
            {payoutEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: ZiBot API */}
        <section id="zibot" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">ZiBot Chatbot API</h2>
          <div className="space-y-12">
            {chatbotEndpoints.map((ep, i) => (
              <EndpointCard key={i} endpoint={ep} copiedStates={copiedStates} copyToClipboard={copyToClipboard} />
            ))}
          </div>
        </section>

        {/* Section: Errors */}
        <section id="errors" className="scroll-mt-6 mb-16">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Error Codes</h2>
          <p className="text-slate-600 dark:text-slate-400 mb-6">
            Standard REST API HTTP response statuses returned on process outcomes:
          </p>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse bg-white dark:bg-slate-900 rounded-xl overflow-hidden shadow-sm border border-slate-200 dark:border-slate-800">
              <thead>
                <tr className="bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-350 text-xs font-semibold uppercase">
                  <th className="px-6 py-4">Status Code</th>
                  <th className="px-6 py-4">Error Name</th>
                  <th className="px-6 py-4">Typical Reason</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-800 text-sm">
                <tr>
                  <td className="px-6 py-4 font-mono font-bold text-red-650">400</td>
                  <td className="px-6 py-4 font-semibold">Bad Request</td>
                  <td className="px-6 py-4 text-slate-500">Missing parameters, invalid types, or request content limit errors.</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 font-mono font-bold text-red-650">401</td>
                  <td className="px-6 py-4 font-semibold">Unauthorized</td>
                  <td className="px-6 py-4 text-slate-500">Bearer token is missing, invalid, or belongs to a disabled account.</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 font-mono font-bold text-red-650">403</td>
                  <td className="px-6 py-4 font-semibold">Forbidden</td>
                  <td className="px-6 py-4 text-slate-500">Resource permissions prevent active user context from accessing.</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 font-mono font-bold text-red-650">404</td>
                  <td className="px-6 py-4 font-semibold">Not Found</td>
                  <td className="px-6 py-4 text-slate-500">Requested resource, payment UTR, or session context key does not exist.</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 font-mono font-bold text-red-650">429</td>
                  <td className="px-6 py-4 font-semibold">Too Many Requests</td>
                  <td className="px-6 py-4 text-slate-500">Rate limits exceeded. Reduce invocation frequencies.</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 font-mono font-bold text-red-650">500</td>
                  <td className="px-6 py-4 font-semibold">Internal Server Error</td>
                  <td className="px-6 py-4 text-slate-500">An unexpected malfunction occurred within payment platform routines.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* Section: Try It Console */}
        <section id="try-it" className="scroll-mt-6 border-t border-slate-350 dark:border-slate-800 pt-12">
          <div className="bg-slate-900 text-slate-100 rounded-2xl shadow-xl overflow-hidden">
            <div className="p-6 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <div className="bg-primary-600 p-2 rounded-lg text-white">
                  <FiCode className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-white text-lg">Interactive API Playground</h3>
                  <p className="text-xs text-slate-500">Test gateway requests live inside your browser</p>
                </div>
              </div>
            </div>

            <form onSubmit={handleTestConsole} className="p-6 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-xs font-semibold uppercase text-slate-400 mb-2">HTTP Method & Path</label>
                  <div className="flex space-x-2">
                    <select
                      value={consoleMethod}
                      onChange={(e) => setConsoleMethod(e.target.value as any)}
                      className="bg-slate-800 border border-slate-700 text-white text-sm rounded-lg p-2.5 focus:ring-primary-500 focus:border-primary-500 font-bold"
                    >
                      <option value="GET">GET</option>
                      <option value="POST">POST</option>
                      <option value="PUT">PUT</option>
                    </select>
                    <input
                      type="text"
                      value={consolePath}
                      onChange={(e) => setConsolePath(e.target.value)}
                      placeholder="/api/payments/check"
                      className="flex-1 bg-slate-800 border border-slate-700 text-white text-sm rounded-lg p-2.5 font-mono focus:ring-primary-500 focus:border-primary-500"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold uppercase text-slate-400 mb-2">Bearer Token (Authorization)</label>
                  <input
                    type="password"
                    value={consoleApiKey}
                    onChange={(e) => setConsoleApiKey(e.target.value)}
                    placeholder="pk_live_..."
                    className="w-full bg-slate-800 border border-slate-700 text-white text-sm rounded-lg p-2.5 font-mono focus:ring-primary-500 focus:border-primary-500"
                  />
                </div>
              </div>

              {consoleMethod !== 'GET' && (
                <div>
                  <label className="block text-xs font-semibold uppercase text-slate-400 mb-2">JSON Request Body</label>
                  <textarea
                    value={consoleBody}
                    onChange={(e) => setConsoleBody(e.target.value)}
                    rows={4}
                    className="w-full bg-slate-800 border border-slate-700 text-white text-sm rounded-lg p-2.5 font-mono focus:ring-primary-500 focus:border-primary-500"
                  />
                </div>
              )}

              <button
                type="submit"
                disabled={consoleLoading}
                className="w-full bg-primary-650 hover:bg-primary-700 disabled:bg-slate-750 text-white font-semibold py-3 px-4 rounded-xl transition duration-150 flex items-center justify-center space-x-2 shadow-lg"
              >
                {consoleLoading ? (
                  <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                ) : (
                  <>
                    <FiSend />
                    <span>Send Request to Live Endpoint</span>
                  </>
                )}
              </button>
            </form>

            {consoleResponse && (
              <div className="p-6 bg-slate-950 border-t border-slate-800 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold uppercase text-slate-450">Server Response</span>
                  {consoleResponse.status && (
                    <span
                      className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                        consoleResponse.status < 300
                          ? 'bg-emerald-500/20 text-emerald-400'
                          : 'bg-red-500/20 text-red-400'
                      }`}
                    >
                      HTTP {consoleResponse.status} {consoleResponse.statusText}
                    </span>
                  )}
                </div>
                <pre className="bg-slate-900 border border-slate-850 p-4 rounded-xl font-mono text-xs overflow-x-auto text-slate-300">
                  {JSON.stringify(consoleResponse.data || consoleResponse, null, 2)}
                </pre>
              </div>
            )}
          </div>
        </section>
      </main>
    </div>
  );
}

function EndpointCard({
  endpoint,
  copiedStates,
  copyToClipboard
}: {
  endpoint: Endpoint;
  copiedStates: { [key: string]: boolean };
  copyToClipboard: (text: string, id: string) => void;
}) {
  const methodColors = {
    GET: 'bg-emerald-500/10 text-emerald-650 dark:text-emerald-400 border-emerald-500/20',
    POST: 'bg-blue-500/10 text-blue-650 dark:text-blue-400 border-blue-500/20',
    PUT: 'bg-amber-500/10 text-amber-650 dark:text-amber-400 border-amber-500/20'
  };

  const id = `${endpoint.method}-${endpoint.path}`;

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm hover:shadow-md transition overflow-hidden">
      {/* Top Banner */}
      <div className="p-6 border-b border-slate-100 dark:border-slate-800/80 flex flex-wrap gap-4 items-center justify-between bg-slate-50/50 dark:bg-slate-900/50">
        <div className="flex items-center space-x-3 flex-1 min-w-0">
          <span className={`text-xs font-bold px-3 py-1.5 rounded-lg border ${methodColors[endpoint.method]}`}>
            {endpoint.method}
          </span>
          <code className="text-sm font-mono font-semibold text-slate-900 dark:text-white truncate">
            {endpoint.path}
          </code>
        </div>
        <div className="flex items-center space-x-2">
          <span className="text-xs bg-slate-200/60 dark:bg-slate-800 text-slate-650 dark:text-slate-400 px-2.5 py-1 rounded-full font-medium">
            Auth: {endpoint.authType}
          </span>
        </div>
      </div>

      <div className="p-6 space-y-6">
        <div>
          <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{endpoint.description}</p>
        </div>

        {/* Request Query/Body Params */}
        {endpoint.bodyParams && endpoint.bodyParams.length > 0 && (
          <div>
            <h4 className="text-xs font-bold uppercase text-slate-400 tracking-wider mb-3">Request Body Properties</h4>
            <div className="overflow-x-auto border border-slate-150 dark:border-slate-800 rounded-xl">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-850 text-slate-500 dark:text-slate-400 uppercase font-semibold border-b border-slate-150 dark:border-slate-800">
                    <th className="px-4 py-3">Property</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Requirement</th>
                    <th className="px-4 py-3">Description</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-150 dark:divide-slate-800">
                  {endpoint.bodyParams.map((param, index) => (
                    <tr key={index} className="hover:bg-slate-50/50 dark:hover:bg-slate-850/20">
                      <td className="px-4 py-3 font-mono font-bold text-slate-900 dark:text-white">{param.name}</td>
                      <td className="px-4 py-3 text-slate-550 dark:text-slate-400 font-mono">{param.type}</td>
                      <td className="px-4 py-3">
                        {param.required ? (
                          <span className="text-red-500 font-semibold bg-red-500/10 px-2 py-0.5 rounded">required</span>
                        ) : (
                          <span className="text-slate-400 bg-slate-1050 px-2 py-0.5 rounded">optional</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-slate-500">{param.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Query Params */}
        {endpoint.queryParams && endpoint.queryParams.length > 0 && (
          <div>
            <h4 className="text-xs font-bold uppercase text-slate-400 tracking-wider mb-3">Query Parameters</h4>
            <div className="overflow-x-auto border border-slate-150 dark:border-slate-800 rounded-xl">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-850 text-slate-500 dark:text-slate-400 uppercase font-semibold border-b border-slate-150 dark:border-slate-800">
                    <th className="px-4 py-3">Param</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Requirement</th>
                    <th className="px-4 py-3">Description</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-150 dark:divide-slate-800">
                  {endpoint.queryParams.map((param, index) => (
                    <tr key={index} className="hover:bg-slate-50/50 dark:hover:bg-slate-850/20">
                      <td className="px-4 py-3 font-mono font-bold text-slate-900 dark:text-white">{param.name}</td>
                      <td className="px-4 py-3 text-slate-550 dark:text-slate-400 font-mono">{param.type}</td>
                      <td className="px-4 py-3">
                        {param.required ? (
                          <span className="text-red-500 font-semibold bg-red-500/10 px-2 py-0.5 rounded">required</span>
                        ) : (
                          <span className="text-slate-400 bg-slate-1050 px-2 py-0.5 rounded">optional</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-slate-500">{param.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Request / Response Tab Code Blocks */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
          {endpoint.requestExample && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs font-semibold text-slate-450 uppercase">
                <span>Example Payload</span>
                <button
                  onClick={() => copyToClipboard(JSON.stringify(endpoint.requestExample, null, 2), `${id}-req`)}
                  className="flex items-center space-x-1 hover:text-slate-900 dark:hover:text-white transition"
                >
                  {copiedStates[`${id}-req`] ? <FiCheck className="text-emerald-500" /> : <FiCopy />}
                  <span>{copiedStates[`${id}-req`] ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
              <pre className="bg-slate-900 border border-slate-850 p-4 rounded-xl font-mono text-xs overflow-x-auto text-slate-300 max-h-60">
                {JSON.stringify(endpoint.requestExample, null, 2)}
              </pre>
            </div>
          )}
          
          <div className={endpoint.requestExample ? 'space-y-2' : 'col-span-2 space-y-2'}>
            <div className="flex items-center justify-between text-xs font-semibold text-slate-450 uppercase">
              <span>Example Response</span>
              <button
                onClick={() => copyToClipboard(JSON.stringify(endpoint.responseExample, null, 2), `${id}-resp`)}
                className="flex items-center space-x-1 hover:text-slate-900 dark:hover:text-white transition"
              >
                {copiedStates[`${id}-resp`] ? <FiCheck className="text-emerald-500" /> : <FiCopy />}
                <span>{copiedStates[`${id}-resp`] ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
            <pre className="bg-slate-900 border border-slate-850 p-4 rounded-xl font-mono text-xs overflow-x-auto text-slate-300 max-h-60">
              {JSON.stringify(endpoint.responseExample, null, 2)}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
