import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Fixed Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-black/80 backdrop-blur-xl border-b border-white/10">
        <div className="container mx-auto px-6 py-4">
          <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white transition-colors">
            <ArrowLeft className="w-5 h-5" />
            Back to Home
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="pt-24 pb-16 px-6">
        <div className="container mx-auto max-w-4xl">
          {/* Title Section */}
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms & Conditions</h1>
            <p className="text-gray-400 text-lg">Last updated: 21st November, 2024</p>
          </div>

          {/* Content Sections */}
          <div className="space-y-8">
            {/* Introduction */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">Introduction</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  This document is an electronic record in terms of the Information Technology Act, 2000 and rules
                  thereunder as applicable and amended from time to time, including the Information Technology
                  (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. This electronic record is
                  generated by an electronic system and does not require any physical or digital signatures.
                </p>
                <p>
                  By accepting the terms and conditions on the website of{" "}
                  <a href="https://www.ztake.in" className="text-blue-400 hover:text-blue-300">
                    https://www.ztake.in
                  </a>{" "}
                  ("Ztake Website") or by accessing, using, or availing any part of the Service, the users
                  ("You"/"Merchant") expressly agree to and consent to being irrevocably bound by these "Terms and
                  Conditions" and all of the terms set out herein.
                </p>
                <p>
                  Your acceptance of these Terms and Conditions will operate as a binding agreement between You and
                  Ztake Payments India Private Limited, a company incorporated under the Companies Act, 2013 and having
                  its registered office at Business Hub, Technology Park, Sector 90, Noida, Uttar Pradesh, India 201305
                  ("Ztake" or "Us").
                </p>
              </div>
            </section>

            {/* Registration */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">1. Registration</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <ul className="list-disc list-inside space-y-3">
                  <li>
                    Depending on the services to be availed, You may have to register on the Ztake Website before
                    accessing the complete dashboard made available to You for the rendition of Services by Us to You.
                  </li>
                  <li>
                    By using the Services, You represent and warrant that you are above the age of 18 (eighteen) years,
                    are an Indian citizen, a legal resident of India or a business entity authorised to conduct business
                    in India, and are qualified to enter into a legally binding contract, including the Indian Contract
                    Act, 1872.
                  </li>
                  <li>
                    You must disclose the exact business category(ies) for which you will be utilising the Services.
                  </li>
                  <li>
                    The details that You have utilized for the creation of the login ID and password are privy to You.
                    We have no manner to access the details of Your Login ID or Password. You would be solely
                    responsible for sharing Your login ID or password with anyone other than Yourself.
                  </li>
                  <li>You shall regularly update the passwords.</li>
                </ul>
              </div>
            </section>

            {/* KYC Details */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">
                2. Completion of KYC Details and Acceptance of Contract
              </h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <ul className="list-disc list-inside space-y-3">
                  <li>
                    Your onboarding with Ztake shall take place in accordance with our internal Merchant Onboarding and
                    Know Your Customer Policy as well as guidelines prescribed by the RBI or any other regulatory
                    authority.
                  </li>
                  <li>
                    You shall be required to submit to Ztake all the necessary documents and details as may be required
                    by Ztake to complete Your onboarding in accordance with our internal Merchant Onboarding and Know
                    Your Customer Policy.
                  </li>
                  <li>
                    You warrant that You or Your affiliates or your respective beneficial owners are not politically
                    exposed persons in accordance with the Master Direction – Know Your Customer (KYC) Direction 2016,
                    as amended from time to time.
                  </li>
                  <li>
                    Failure to provide correct details or to not to provide relevant details or to cheat Ztake to
                    provide Services by providing false information, would entitle Ztake to terminate the Services with
                    immediate effect and without any notice whatsoever.
                  </li>
                </ul>
              </div>
            </section>

            {/* Dashboard Access */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">3. Access to Dashboard</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <ul className="list-disc list-inside space-y-3">
                  <li>
                    After You have registered on the Ztake Website, Ztake will provide you with the access to Ztake
                    Platform and the Dashboard. With access to Dashboard, You would be able to activate and deactivate
                    Services that You wish to receive or no longer wish to receive from Us.
                  </li>
                  <li>
                    The Dashboard will be accessible through the login ID and password. Anyone who will have access to
                    the login ID and password will be able to manage and control the Services and the transactions.
                  </li>
                  <li>
                    You shall be solely responsible to supervise the status of Transactions and download reports from
                    the Dashboard on a regular basis.
                  </li>
                </ul>
              </div>
            </section>

            {/* Intellectual Property */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">4. Contents of Ztake Website</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <ul className="list-disc list-inside space-y-3">
                  <li>
                    The contents of the Ztake Website are proprietary to Ztake and You will not have any authority to
                    claim any intellectual property rights, title, or interest in the contents of the Ztake Website.
                  </li>
                  <li>
                    You and We acknowledge that any trademarks, copyrights or patents used or adopted by a Party in the
                    conduct of its business are the sole property of the respective owners.
                  </li>
                  <li>
                    Nothing contained herein shall authorize the Parties to use, apply, invade or in any manner exploit
                    or infringe the Intellectual Property Rights of the other Parties without the prior written consent
                    of the other Party.
                  </li>
                </ul>
              </div>
            </section>

            {/* API Integration */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">5. API Integration with Ztake</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <ul className="list-disc list-inside space-y-3">
                  <li>
                    You shall not integrate with Ztake for any Services or use any plugins or other software development
                    kits unless You have completed the KYC and entered into an appropriate agreement with Us.
                  </li>
                  <li>
                    You shall ensure that Your website or its web application is secured in accordance with the
                    prescribed guidelines issued by the RBI from time to time. You shall not store any card data on Your
                    website or web application.
                  </li>
                  <li>
                    An incident related to breach of data or breach of security shall be informed by the Parties to each
                    other within 24 (twenty-four) hours of such an incident.
                  </li>
                  <li>
                    You shall take due steps to ensure that the transactions are monitored for fraud and anti-money
                    laundering activities in accordance with applicable law.
                  </li>
                </ul>
              </div>
            </section>

            {/* Fraudulent Transactions */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">6. Fraudulent Transactions</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  You shall not engage in any form of fraudulent transactions and use the Services of Ztake for
                  perpetrating a criminal offense in any manner thereof. Any scheme or structure to defraud the Customer
                  by You while using Services of Ztake shall be reported to the relevant law enforcement authorities.
                </p>
                <p className="font-semibold text-white">
                  Ztake reserves the right to close, suspend, limit or put on hold the access to Your account under the
                  following scenarios:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>If KYC credentials are found to be ingenuine or fake</li>
                  <li>Incorrect or untrue disclosure of the nature of business</li>
                  <li>Violation of any provisions of these Terms and Conditions</li>
                  <li>Violation of any applicable laws</li>
                </ul>
              </div>
            </section>

            {/* Representations & Warranties */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">7. Representations & Warranties</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>You represent, warrant, and undertake that:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>You are duly organized and validly existing under the laws of your jurisdiction</li>
                  <li>You have the requisite power and authority to execute and perform your obligations</li>
                  <li>You shall not use the Services for any unlawful or illegal purpose</li>
                  <li>You shall comply with all applicable laws and Card Association Rules</li>
                  <li>You must display the price of services conspicuously and clearly on your site</li>
                  <li>You must maintain a fair return, cancellation or adjustment policy</li>
                  <li>You shall not discriminate against any specific Payment Instrument</li>
                </ul>
              </div>
            </section>

            {/* Confidentiality */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">8. Confidentiality</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  You acknowledge and agree that in connection with the Services, You shall not disclose to any third
                  party, any Confidential Information of Ztake that You may have access to during and in connection with
                  Services hereunder.
                </p>
                <p>
                  You acknowledge that monetary damages may not be a sufficient remedy for unauthorized disclosure of
                  any Confidential Information and that Ztake shall be entitled, without waiving any other rights or
                  remedies, to such injunctive or equitable relief as may be deemed proper.
                </p>
              </div>
            </section>

            {/* Indemnification */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">9. Indemnification</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  You hereby undertake and agree to indemnify, protect against liability and hold harmless Ztake, its
                  affiliates, and their respective directors, employees, officers, agents, representatives, contractors
                  and sub-contractors against all actions, proceedings, claims, liabilities, penalties, demands and
                  costs arising in relation to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Any breach of these Terms and Conditions or Privacy Policy</li>
                  <li>Any business undertaken which is listed in the Negative, Risky and Restricted Categories</li>
                  <li>Any breach of Confidential Information</li>
                  <li>Any actual or alleged violation of applicable laws or Card Association Rules</li>
                  <li>Any wrongful or improper use of Services or Ztake Platform</li>
                  <li>Any violation of third-party rights</li>
                </ul>
              </div>
            </section>

            {/* Limitation of Liability */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">10. Limitation of Liability</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  The aggregate liability of Ztake to You from any cause whatsoever shall not, in any event, exceed the
                  sum equivalent to the preceding 1 (one) month's aggregate Consideration earned by Ztake from the date
                  of occurrence of such liability.
                </p>
                <p className="font-semibold text-white">Ztake shall not be liable for:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Loss of profits or business opportunities</li>
                  <li>Any failure or delay in the use of the Ztake Website</li>
                  <li>Any damages to or viruses that may infect your computer equipment</li>
                  <li>Any error in submitting payment instructions</li>
                  <li>Providing inadequate or incorrect information</li>
                </ul>
              </div>
            </section>

            {/* Disclaimer */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">11. Disclaimer</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  Ztake will make all reasonable efforts to provide uninterrupted service subject to downtime and
                  regular maintenance. However, You acknowledge that Ztake Website, Services, and the Acquiring Bank's
                  Services may not be uninterrupted or error-free and all services are provided on an "as is" basis.
                </p>
                <p>
                  Ztake shall not be responsible for any losses sustained through the use of counterfeit or stolen bank
                  cards, fraudulent electronic transactions, or quality and service-related claims pertaining to the
                  Merchant Services.
                </p>
              </div>
            </section>

            {/* Force Majeure */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">12. Force Majeure</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  Force Majeure shall be any event or occurrence which cannot be foreseen and is beyond the control of
                  Ztake, including but not limited to acts of governmental policy/authority, fires, floods, earthquakes,
                  natural disasters, explosions, general strikes, riots, war, rebellion, sabotage, computer hacking, and
                  computer crashes.
                </p>
                <p>
                  In case of a Force Majeure event, Ztake shall not be liable to You for its delay in the performance
                  of, or non-performance, of its obligations under these Terms and Conditions.
                </p>
              </div>
            </section>

            {/* Data Protection */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">13. Data Protection</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  You shall ensure such administrative, technical, physical safeguards and processes, procedures, and
                  checks including to secure the information which is received from any Customer in relation to a card
                  as may be required under applicable law.
                </p>
                <p className="font-semibold text-white">The safeguards shall be designed to:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Protect the security and confidentiality of Customer information</li>
                  <li>Ensure protection against anticipated threats or hazards</li>
                  <li>Protection against unauthorized access to Customer information</li>
                  <li>Ensure proper and secure disposal of data</li>
                </ul>
              </div>
            </section>

            {/* Anti-Bribery */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">14. Anti-Bribery and Sanctions Laws</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  You shall not permit or engage in any unethical practices, corruption, extortion, or bribery in any
                  capacity. You shall not offer, give, or authorize any gift, loan, fee, reward, bribe, or other
                  advantage to any Customer, government official, government employee, or Ztake's employee to improperly
                  influence any action or decision.
                </p>
                <p>
                  You shall follow applicable national and international anti-corruption laws, including the Prevention
                  of Corruption Act, 1988, and U.S. Foreign Corrupt Practices Act.
                </p>
              </div>
            </section>

            {/* Miscellaneous */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">15. Miscellaneous</h2>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <ul className="list-disc list-inside space-y-3">
                  <li>
                    Ztake may assign, in whole or in part, the benefits or obligations under these Terms and Conditions
                    by providing a 30 (thirty) days prior intimation.
                  </li>
                  <li>
                    You shall not assign, in whole or in part, the benefits or obligations under these Terms and
                    Conditions without prior written approval of Ztake.
                  </li>
                  <li>
                    The relationship between You and Us are on a principal-to-principal basis. Nothing contained herein
                    shall be deemed to create any association, partnership, joint venture or relationship of principal
                    and agent.
                  </li>
                  <li>
                    Ztake reserves the right to make changes to the Ztake Website, these Terms and Conditions, and the
                    Privacy Policy at its sole discretion at any time.
                  </li>
                </ul>
              </div>
            </section>

            {/* Negative Categories */}
            <section className="glass-card p-8 rounded-2xl">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">
                Attachment A: Negative, Risky and Restricted Categories
              </h2>
              <div className="space-y-6 text-gray-300 leading-relaxed">
                <div>
                  <h3 className="text-xl font-semibold text-white mb-3">Negative Categories (Prohibited)</h3>
                  <p className="mb-2">Products and services that are banned include:</p>
                  <ul className="list-disc list-inside space-y-1 text-sm">
                    <li>Adult goods and services, pornography</li>
                    <li>Alcohol and alcoholic beverages</li>
                    <li>Drugs and drug paraphernalia</li>
                    <li>Weapons, firearms, ammunition</li>
                    <li>Counterfeit and unauthorized goods</li>
                    <li>Cryptocurrency exchanges and trading platforms</li>
                    <li>Gambling and gaming services</li>
                    <li>Illegal goods and offensive materials</li>
                    <li>Tobacco and cigarettes</li>
                    <li>Multi-Level Marketing and Ponzi schemes</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-xl font-semibold text-white mb-3">Risky Categories (High Risk)</h3>
                  <p className="mb-2">Merchants in these segments are considered high risk:</p>
                  <ul className="list-disc list-inside space-y-1 text-sm">
                    <li>Financial Services</li>
                    <li>Pharmacy</li>
                    <li>Tours and Travel</li>
                    <li>SaaS</li>
                    <li>Jewelry and Digital Gold</li>
                    <li>Insurance and Forex</li>
                    <li>Digital Lending</li>
                    <li>Stock Market and Mutual Funds</li>
                    <li>Online Gaming</li>
                    <li>NBFC and Chit Funds</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-xl font-semibold text-white mb-3">Restricted Categories (Require Approval)</h3>
                  <p className="mb-2">These categories require further approvals from the risk team:</p>
                  <ul className="list-disc list-inside space-y-1 text-sm">
                    <li>Online Gaming</li>
                    <li>Digital Lending</li>
                    <li>Chit Funds</li>
                    <li>DMT Merchants</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Contact Information */}
            <section className="glass-card p-8 rounded-2xl bg-gradient-to-br from-blue-600/10 to-purple-600/10">
              <h2 className="text-2xl font-semibold mb-4 text-blue-400">Contact Information</h2>
              <div className="space-y-3 text-gray-300">
                <p className="font-semibold text-white">For Any Queries / Details Users Can Contact:</p>
                <div className="space-y-1">
                  <p className="font-semibold">Ztake Payments Pvt Ltd</p>
                  <p>Business Hub, Technology Park</p>
                  <p>Sector 90, Noida</p>
                  <p>Uttar Pradesh, India 201305</p>
                </div>
                <div className="pt-4 space-y-1">
                  <p>
                    <span className="font-semibold">Phone:</span>{" "}
                    <a href="tel:+919220592512" className="text-blue-400 hover:text-blue-300">
                      +91 9220592512
                    </a>
                  </p>
                  <p>
                    <span className="font-semibold">Email:</span>{" "}
                    <a href="mailto:sales@ztake.in" className="text-blue-400 hover:text-blue-300">
                      sales@ztake.in
                    </a>
                  </p>
                </div>
              </div>
            </section>

            {/* Additional Note */}
            <div className="text-center text-gray-500 text-sm pt-8">
              <p>
                By using our services, you acknowledge that you have read, understood, and agree to be bound by these
                Terms and Conditions.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
